defaults:
  - backbone: vgg19
  - visdom: visdom

# Directories
dirs:
  data: ./data

# Files
files:
  log_file: ${hydra:job.name}.log

random_seed: 26
data_loader_workers: 4
mode:
  train:
    batch_size: 64
    max_epochs: 3
    shuffle: True
  val:
    batch_size: 64
    max_epochs: 1
    shuffle: False

# TODO: Copy in Slack API key using hydra ... copy_env
